/**
 * Do not edit directly, this file was auto-generated.
 * Generated on <stripped>
 *
 * Kong Konnect Design Tokens
 * GitHub: https://github.com/Kong/design-tokens/tree/main/packages/design-tokens
 * License: Apache-2.0
 */

export const KUI_COLOR_BACKGROUND = "#ffffff"; // Default background color for containers (white).
export const KUI_COLOR_BACKGROUND_DANGER = "#d60027"; // Background color for danger actions or messages (red.60).
export const KUI_COLOR_BACKGROUND_DANGER_STRONG = "#ad000e"; // Strong background color for danger actions or messages (red.70).
export const KUI_COLOR_BACKGROUND_DANGER_STRONGER = "#850000"; // Stronger background color for danger actions or messages (red.80).
export const KUI_COLOR_BACKGROUND_DANGER_STRONGEST = "#5c0000"; // Strongest background color for danger actions or messages (red.90).
export const KUI_COLOR_BACKGROUND_DANGER_WEAK = "#ff3954"; // Weak background color for danger actions or messages (red.40).
export const KUI_COLOR_BACKGROUND_DANGER_WEAKER = "#ffabab"; // Weaker background color for danger actions or messages (red.20).
export const KUI_COLOR_BACKGROUND_DANGER_WEAKEST = "#ffe5e5"; // Weakest background color for danger actions or messages (red.10).
export const KUI_COLOR_BACKGROUND_DECORATIVE_AQUA_WEAKEST = "#ecfcff"; // Weakest background color for decorative purposes (aqua.10).
export const KUI_COLOR_BACKGROUND_DECORATIVE_PURPLE = "#6f28ff"; // Background color for decorative purposes (purple.60).
export const KUI_COLOR_BACKGROUND_DECORATIVE_PURPLE_WEAKEST = "#f1f0ff"; // Weakest background color for decorative purposes (purple.10).
export const KUI_COLOR_BACKGROUND_DISABLED = "#e0e4ea"; // Background color for disabled elements (gray.20).
export const KUI_COLOR_BACKGROUND_INFO = "#0044f4"; // Background color for info elements (blue.60).
export const KUI_COLOR_BACKGROUND_INFO_STRONG = "#0030cc"; // Strong background color for info elements (blue.70).
export const KUI_COLOR_BACKGROUND_INFO_STRONGER = "#002099"; // Stronger background color for info elements (blue.80).
export const KUI_COLOR_BACKGROUND_INFO_STRONGEST = "#001466"; // Strongest background color for info elements (blue.90).
export const KUI_COLOR_BACKGROUND_INFO_WEAK = "#5f9aff"; // Weak background color for info elements (blue.40).
export const KUI_COLOR_BACKGROUND_INFO_WEAKER = "#bee2ff"; // Weaker background color for info elements (blue.20).
export const KUI_COLOR_BACKGROUND_INFO_WEAKEST = "#eefaff"; // Weakest background color for info elements (blue.10).
export const KUI_COLOR_BACKGROUND_INVERSE = "#000933"; // Inverse background color for containers (blue.100)
export const KUI_COLOR_BACKGROUND_NEUTRAL = "#6c7489"; // Background color for neutral elements (gray.60).
export const KUI_COLOR_BACKGROUND_NEUTRAL_STRONG = "#52596e"; // Strong background color for neutral elements (gray.70).
export const KUI_COLOR_BACKGROUND_NEUTRAL_STRONGER = "#3a3f51"; // Stronger background color for neutral elements (gray.80).
export const KUI_COLOR_BACKGROUND_NEUTRAL_STRONGEST = "#232633"; // Strongest background color for neutral elements (gray.90).
export const KUI_COLOR_BACKGROUND_NEUTRAL_WEAK = "#afb7c5"; // Weak background color for neutral elements (gray.40).
export const KUI_COLOR_BACKGROUND_NEUTRAL_WEAKER = "#e0e4ea"; // Weaker background color for neutral elements (gray.20).
export const KUI_COLOR_BACKGROUND_NEUTRAL_WEAKEST = "#f9fafb"; // Weakest background color for neutral elements (gray.10).
export const KUI_COLOR_BACKGROUND_OVERLAY = "rgba(0, 9, 51, 0.6)"; // Overlay background color (rgba(0, 9, 51, 0.6))
export const KUI_COLOR_BACKGROUND_PRIMARY = "#0044f4"; // Background color for primary actions or messages (blue.60).
export const KUI_COLOR_BACKGROUND_PRIMARY_STRONG = "#0030cc"; // Strong background color for primary actions or messages (blue.70).
export const KUI_COLOR_BACKGROUND_PRIMARY_STRONGER = "#002099"; // Stronger background color for primary actions or messages (blue.80).
export const KUI_COLOR_BACKGROUND_PRIMARY_STRONGEST = "#001466"; // Strongest background color for primary actions or messages (blue.90).
export const KUI_COLOR_BACKGROUND_PRIMARY_WEAK = "#5f9aff"; // Weak background color for primary actions or messages (blue.40).
export const KUI_COLOR_BACKGROUND_PRIMARY_WEAKER = "#bee2ff"; // Weaker background color for primary actions or messages (blue.20).
export const KUI_COLOR_BACKGROUND_PRIMARY_WEAKEST = "#eefaff"; // Weakest background color for primary actions or messages (blue.10)
export const KUI_COLOR_BACKGROUND_SUCCESS = "#007d60"; // Background color for success elements (green.60).
export const KUI_COLOR_BACKGROUND_SUCCESS_STRONG = "#005944"; // Strong background color for success elements (green.70).
export const KUI_COLOR_BACKGROUND_SUCCESS_STRONGER = "#004737"; // Stronger background color for success elements (green.80).
export const KUI_COLOR_BACKGROUND_SUCCESS_STRONGEST = "#003629"; // Strongest background color for success elements (green.90).
export const KUI_COLOR_BACKGROUND_SUCCESS_WEAK = "#00d6a4"; // Weak background color for success elements (green.40).
export const KUI_COLOR_BACKGROUND_SUCCESS_WEAKER = "#b5ffee"; // Weaker background color for success elements (green.20).
export const KUI_COLOR_BACKGROUND_SUCCESS_WEAKEST = "#ecfffb"; // Weakest background color for success elements (green.10).
export const KUI_COLOR_BACKGROUND_TRANSPARENT = "rgba(0, 0, 0, 0)"; // Transparent background color (transparent).
export const KUI_COLOR_BACKGROUND_WARNING = "#995c00"; // Background color for warning elements (yellow.60).
export const KUI_COLOR_BACKGROUND_WARNING_STRONG = "#804400"; // Strong background color for warning elements (yellow.70).
export const KUI_COLOR_BACKGROUND_WARNING_STRONGER = "#662d00"; // Stronger background color for warning elements (yellow.80).
export const KUI_COLOR_BACKGROUND_WARNING_STRONGEST = "#4d1b00"; // Strongest background color for warning elements (yellow.90).
export const KUI_COLOR_BACKGROUND_WARNING_WEAK = "#ffc400"; // Weak background color for warning elements (yellow.40).
export const KUI_COLOR_BACKGROUND_WARNING_WEAKER = "#fff296"; // Weaker background color for warning elements (yellow.20).
export const KUI_COLOR_BACKGROUND_WARNING_WEAKEST = "#fffce0"; // Weakest background color for warning elements (yellow.10).
export const KUI_COLOR_BORDER = "#e0e4ea"; // Default border color for containers (gray.20).
export const KUI_COLOR_BORDER_DANGER = "#d60027"; // Border color for danger actions or messages (red.60).
export const KUI_COLOR_BORDER_DANGER_STRONG = "#ad000e"; // Strong border color for danger actions or messages (red.70).
export const KUI_COLOR_BORDER_DANGER_STRONGER = "#850000"; // Stronger border color for danger actions or messages (red.80).
export const KUI_COLOR_BORDER_DANGER_STRONGEST = "#5c0000"; // Strongest border color for danger actions or messages (red.90).
export const KUI_COLOR_BORDER_DANGER_WEAK = "#ff3954"; // Weak border color for danger actions or messages (red.40).
export const KUI_COLOR_BORDER_DANGER_WEAKER = "#ffabab"; // Weaker border color for danger actions or messages (red.20).
export const KUI_COLOR_BORDER_DANGER_WEAKEST = "#ffe5e5"; // Weakest border color for danger actions or messages (red.10).
export const KUI_COLOR_BORDER_DECORATIVE_PURPLE = "#6f28ff"; // Border color for decorative purposes (purple.60).
export const KUI_COLOR_BORDER_DISABLED = "#e0e4ea"; // Border color for disabled elements (gray.20).
export const KUI_COLOR_BORDER_INVERSE = "rgba(255, 255, 255, 0.2)"; // Inverse border color (rgba(255, 255, 255, 0.2)).
export const KUI_COLOR_BORDER_NEUTRAL = "#6c7489"; // Border color for neutral elements (gray.60)
export const KUI_COLOR_BORDER_NEUTRAL_STRONG = "#52596e"; // Strong border color for neutral elements (gray.70)
export const KUI_COLOR_BORDER_NEUTRAL_STRONGER = "#3a3f51"; // Stronger border color for neutral elements (gray.80)
export const KUI_COLOR_BORDER_NEUTRAL_STRONGEST = "#232633"; // Strongest border color for neutral elements (gray.90)
export const KUI_COLOR_BORDER_NEUTRAL_WEAK = "#afb7c5"; // Weak border color for neutral elements (gray.40)
export const KUI_COLOR_BORDER_NEUTRAL_WEAKER = "#e0e4ea"; // Weaker border color for neutral elements (gray.20)
export const KUI_COLOR_BORDER_NEUTRAL_WEAKEST = "#f9fafb"; // Weakest border color for neutral elements (gray.10)
export const KUI_COLOR_BORDER_PRIMARY = "#0044f4"; // Border color for primary actions or messages (blue.60).
export const KUI_COLOR_BORDER_PRIMARY_STRONG = "#0030cc"; // Strong border color for primary actions or messages (blue.70).
export const KUI_COLOR_BORDER_PRIMARY_STRONGER = "#002099"; // Stronger border color for primary actions or messages (blue.80).
export const KUI_COLOR_BORDER_PRIMARY_STRONGEST = "#001466"; // Strongest border color for primary actions or messages (blue.90).
export const KUI_COLOR_BORDER_PRIMARY_WEAK = "#5f9aff"; // Weak border color for primary actions or messages (blue.40).
export const KUI_COLOR_BORDER_PRIMARY_WEAKER = "#bee2ff"; // Weaker border color for primary actions or messages (blue.20).
export const KUI_COLOR_BORDER_PRIMARY_WEAKEST = "#eefaff"; // Weakest border color for primary actions or messages (blue.10).
export const KUI_COLOR_BORDER_TRANSPARENT = "rgba(0, 0, 0, 0)"; // Transparent border color (transparent).
export const KUI_COLOR_TEXT = "#000933"; // Default text color (blue.100).
export const KUI_COLOR_TEXT_DANGER = "#d60027"; // Text color for danger actions or messages (red.60).
export const KUI_COLOR_TEXT_DANGER_STRONG = "#ad000e"; // Strong text color for danger actions or messages (red.70).
export const KUI_COLOR_TEXT_DANGER_STRONGER = "#850000"; // Stronger text color for danger actions or messages (red.80).
export const KUI_COLOR_TEXT_DANGER_STRONGEST = "#5c0000"; // Strongest text color for danger actions or messages (red.90).
export const KUI_COLOR_TEXT_DANGER_WEAK = "#ff3954"; // Weak text color for danger actions or messages (red.40).
export const KUI_COLOR_TEXT_DANGER_WEAKER = "#ffabab"; // Weaker text color for danger actions or messages (red.20).
export const KUI_COLOR_TEXT_DANGER_WEAKEST = "#ffe5e5"; // Weakest text color for danger actions or messages (red.10).
export const KUI_COLOR_TEXT_DECORATIVE_AQUA = "#00abd2"; // Text color for decorative purposes (aqua.50).
export const KUI_COLOR_TEXT_DECORATIVE_PINK = "#d60067"; // Text color for decorative purposes (pink.60).
export const KUI_COLOR_TEXT_DECORATIVE_PURPLE = "#6f28ff"; // Text color for decorative purposes (purple.60).
export const KUI_COLOR_TEXT_DECORATIVE_PURPLE_STRONG = "#5e00f5"; // Strong text color for decorative purposes (purple.70).
export const KUI_COLOR_TEXT_DISABLED = "#afb7c5"; // Text color for disabled elements (gray.40).
export const KUI_COLOR_TEXT_INFO = "#0044f4"; // Text color for info elements (blue.60).
export const KUI_COLOR_TEXT_INFO_STRONG = "#0030cc"; // Strong text color for info elements (blue.70).
export const KUI_COLOR_TEXT_INFO_STRONGER = "#002099"; // Stronger text color for info elements (blue.80).
export const KUI_COLOR_TEXT_INFO_STRONGEST = "#001466"; // Strongest text color for info elements (blue.90).
export const KUI_COLOR_TEXT_INFO_WEAK = "#5f9aff"; // Weak text color for info elements (blue.40).
export const KUI_COLOR_TEXT_INFO_WEAKER = "#bee2ff"; // Weaker text color for info elements (blue.20).
export const KUI_COLOR_TEXT_INFO_WEAKEST = "#eefaff"; // Weakest text color for info elements (blue.10).
export const KUI_COLOR_TEXT_INVERSE = "#ffffff"; // Inverse text color (white).
export const KUI_COLOR_TEXT_NEUTRAL = "#6c7489"; // Text color for neutral elements (gray.60).
export const KUI_COLOR_TEXT_NEUTRAL_STRONG = "#52596e"; // Strong text color for neutral elements (gray.70).
export const KUI_COLOR_TEXT_NEUTRAL_STRONGER = "#3a3f51"; // Stronger text color for neutral elements (gray.80).
export const KUI_COLOR_TEXT_NEUTRAL_STRONGEST = "#232633"; // Strongest text color for neutral elements (gray.90).
export const KUI_COLOR_TEXT_NEUTRAL_WEAK = "#afb7c5"; // Weak text color for neutral elements (gray.40).
export const KUI_COLOR_TEXT_NEUTRAL_WEAKER = "#e0e4ea"; // Weaker text color for neutral elements (gray.20).
export const KUI_COLOR_TEXT_NEUTRAL_WEAKEST = "#f9fafb"; // Weakest text color for neutral elements (gray.10).
export const KUI_COLOR_TEXT_PRIMARY = "#0044f4"; // Text color for primary actions or messages (blue.60).
export const KUI_COLOR_TEXT_PRIMARY_STRONG = "#0030cc"; // Strong text color for primary actions or messages (blue.70).
export const KUI_COLOR_TEXT_PRIMARY_STRONGER = "#002099"; // Stronger text color for primary actions or messages (blue.80).
export const KUI_COLOR_TEXT_PRIMARY_STRONGEST = "#001466"; // Strongest text color for primary actions or messages (blue.90).
export const KUI_COLOR_TEXT_PRIMARY_WEAK = "#5f9aff"; // Weak text color for primary actions or messages (blue.40).
export const KUI_COLOR_TEXT_PRIMARY_WEAKER = "#bee2ff"; // Weaker text color for primary actions or messages (blue.20).
export const KUI_COLOR_TEXT_PRIMARY_WEAKEST = "#eefaff"; // Weakest text color for primary actions or messages (blue.10).
export const KUI_COLOR_TEXT_SUCCESS = "#007d60"; // Text color for success elements (green.60).
export const KUI_COLOR_TEXT_SUCCESS_STRONG = "#005944"; // Strong text color for success elements (green.70).
export const KUI_COLOR_TEXT_SUCCESS_STRONGER = "#004737"; // Stronger text color for success elements (green.80).
export const KUI_COLOR_TEXT_SUCCESS_STRONGEST = "#003629"; // Stronger text color for success elements (green.90).
export const KUI_COLOR_TEXT_SUCCESS_WEAK = "#00d6a4"; // Weak text color for success elements (green.40).
export const KUI_COLOR_TEXT_SUCCESS_WEAKER = "#b5ffee"; // Weaker text color for success elements (green.20).
export const KUI_COLOR_TEXT_SUCCESS_WEAKEST = "#ecfffb"; // Weakest text color for success elements (green.10).
export const KUI_COLOR_TEXT_WARNING = "#995c00"; // Text color for warning elements (yellow.60).
export const KUI_COLOR_TEXT_WARNING_STRONG = "#804400"; // Strong text color for warning elements (yellow.70).
export const KUI_COLOR_TEXT_WARNING_STRONGER = "#662d00"; // Stronger text color for warning elements (yellow.80).
export const KUI_COLOR_TEXT_WARNING_STRONGEST = "#4d1b00"; // Strongest text color for warning elements (yellow.90).
export const KUI_COLOR_TEXT_WARNING_WEAK = "#ffc400"; // Weak text color for warning elements (yellow.40).
export const KUI_COLOR_TEXT_WARNING_WEAKER = "#fff296"; // Weaker text color for warning elements (yellow.20).
export const KUI_COLOR_TEXT_WARNING_WEAKEST = "#fffce0"; // Weakest text color for warning elements (yellow.10).
export const KUI_ANIMATION_DURATION_20 = "0.2s"; // Default transition timing
export const KUI_BORDER_RADIUS_0 = "0px"; // 0px border radius.
export const KUI_BORDER_RADIUS_10 = "2px"; // 2px border radius.
export const KUI_BORDER_RADIUS_20 = "4px"; // 4px border radius.
export const KUI_BORDER_RADIUS_30 = "6px"; // 6px border radius.
export const KUI_BORDER_RADIUS_40 = "8px"; // 8px border radius.
export const KUI_BORDER_RADIUS_50 = "10px"; // 10px border radius.
export const KUI_BORDER_RADIUS_CIRCLE = "50%"; // 50% border radius used to create circles.
export const KUI_BORDER_RADIUS_ROUND = "100px"; // 100px border radius used to create pill shapes.
export const KUI_BORDER_WIDTH_0 = "0px"; // 0px border width.
export const KUI_BORDER_WIDTH_10 = "1px"; // 1px border width.
export const KUI_BORDER_WIDTH_20 = "2px"; // 2px border width.
export const KUI_BORDER_WIDTH_30 = "4px"; // 4px border width.
export const KUI_BREAKPOINT_MOBILE = "640px"; // Used for larger mobile screens. Any viewport width under this value is considered mobile.
export const KUI_BREAKPOINT_PHABLET = "768px"; // Used for tablet screens.
export const KUI_BREAKPOINT_TABLET = "1024px"; // Used for larger tablet screens. Any viewport width less than this value will likely show a mobile layout. Any viewport width this value and greater will likely show a desktop layout.
export const KUI_BREAKPOINT_LAPTOP = "1280px"; // Used for standard desktop screens.
export const KUI_BREAKPOINT_DESKTOP = "1536px"; // Used for larger desktop screens.
export const KUI_METHOD_COLOR_BACKGROUND_CONNECT = "#f1f0ff"; // Background color for the CONNECT method (purple.10).
export const KUI_METHOD_COLOR_BACKGROUND_DELETE = "#ffe5e5"; // Background color for the DELETE method (red.10).
export const KUI_METHOD_COLOR_BACKGROUND_GET = "#eefaff"; // Background color for the GET method (blue.10).
export const KUI_METHOD_COLOR_BACKGROUND_HEAD = "#52596e"; // Background color for the HEAD method (gray.70).
export const KUI_METHOD_COLOR_BACKGROUND_OPTIONS = "#e0e4ea"; // Background color for the OPTIONS method (gray.20).
export const KUI_METHOD_COLOR_BACKGROUND_PATCH = "#ecfcff"; // Background color for the PATCH method (aqua.10).
export const KUI_METHOD_COLOR_BACKGROUND_POST = "#ecfffb"; // Background color for the POST method (green.10).
export const KUI_METHOD_COLOR_BACKGROUND_PUT = "#fffce0"; // Background color for the PUT method (yellow.10).
export const KUI_METHOD_COLOR_BACKGROUND_TRACE = "#fff0f7"; // Background color for the TRACE method (pink.10).
export const KUI_METHOD_COLOR_TEXT_CONNECT = "#6f28ff"; // Text color for the CONNECT method (purple.60).
export const KUI_METHOD_COLOR_TEXT_CONNECT_STRONG = "#5e00f5"; // Strong text color for the CONNECT method (purple.70).
export const KUI_METHOD_COLOR_TEXT_DELETE = "#d60027"; // Text color for the DELETE method (red.60).
export const KUI_METHOD_COLOR_TEXT_DELETE_STRONG = "#ad000e"; // Strong text color for the DELETE method (red.70).
export const KUI_METHOD_COLOR_TEXT_GET = "#0044f4"; // Text color for the GET method (blue.60).
export const KUI_METHOD_COLOR_TEXT_GET_STRONG = "#0030cc"; // Strong text color for the GET method (blue.70).
export const KUI_METHOD_COLOR_TEXT_HEAD = "#e0e4ea"; // Text color for the HEAD method (gray.20).
export const KUI_METHOD_COLOR_TEXT_HEAD_STRONG = "#afb7c5"; // Strong text color for the HEAD method (gray.40).
export const KUI_METHOD_COLOR_TEXT_OPTIONS = "#52596e"; // Text color for the OPTIONS method (gray.70).
export const KUI_METHOD_COLOR_TEXT_OPTIONS_STRONG = "#3a3f51"; // Strong text color for the OPTIONS method (gray.80).
export const KUI_METHOD_COLOR_TEXT_PATCH = "#00819d"; // Text color for the PATCH method (aqua.60).
export const KUI_METHOD_COLOR_TEXT_PATCH_STRONG = "#00647a"; // Strong text color for the PATCH method (aqua.70).
export const KUI_METHOD_COLOR_TEXT_POST = "#007d60"; // Text color for the POST method (green.60).
export const KUI_METHOD_COLOR_TEXT_POST_STRONG = "#005944"; // Strong text color for the POST method (green.70).
export const KUI_METHOD_COLOR_TEXT_PUT = "#995c00"; // Text color for the PUT method (yellow.60).
export const KUI_METHOD_COLOR_TEXT_PUT_STRONG = "#804400"; // Strong text color for the PUT method (yellow.70).
export const KUI_METHOD_COLOR_TEXT_TRACE = "#d60067"; // Text color for the TRACE method (pink.60).
export const KUI_METHOD_COLOR_TEXT_TRACE_STRONG = "#ad0053"; // Strong text color for the TRACE method (pink.70).
export const KUI_STATUS_COLOR_100 = "#bee2ff"; // Color representing response status code 100 (blue.20).
export const KUI_STATUS_COLOR_101 = "#8fc1ff"; // Color representing response status code 101 (blue.30).
export const KUI_STATUS_COLOR_102 = "#5f9aff"; // Color representing response status code 102 (blue.40).
export const KUI_STATUS_COLOR_103 = "#306fff"; // Color representing response status code 103 (blue.50).
export const KUI_STATUS_COLOR_200 = "#b5ffee"; // Color representing response status code 200 (green.20).
export const KUI_STATUS_COLOR_201 = "#00fabe"; // Color representing response status code 201 (green.30).
export const KUI_STATUS_COLOR_202 = "#00d6a4"; // Color representing response status code 202 (green.40).
export const KUI_STATUS_COLOR_203 = "#00a17b"; // Color representing response status code 203 (green.50).
export const KUI_STATUS_COLOR_204 = "#007d60"; // Color representing response status code 204 (green.60).
export const KUI_STATUS_COLOR_205 = "#005944"; // Color representing response status code 205 (green.70).
export const KUI_STATUS_COLOR_206 = "#b5ffee"; // Color representing response status code 206 (green.20).
export const KUI_STATUS_COLOR_207 = "#00fabe"; // Color representing response status code 207 (green.30).
export const KUI_STATUS_COLOR_208 = "#b5ffee"; // Color representing response status code 208 (green.40).
export const KUI_STATUS_COLOR_226 = "#00a17b"; // Color representing response status code 226 (green.50).
export const KUI_STATUS_COLOR_300 = "#fff296"; // Color representing response status code 100 (yellow.20).
export const KUI_STATUS_COLOR_301 = "#ffe04b"; // Color representing response status code 101 (yellow.30).
export const KUI_STATUS_COLOR_302 = "#ffc400"; // Color representing response status code 102 (yellow.40).
export const KUI_STATUS_COLOR_303 = "#b37600"; // Color representing response status code 103 (yellow.50).
export const KUI_STATUS_COLOR_304 = "#995c00"; // Color representing response status code 103 (yellow.60).
export const KUI_STATUS_COLOR_305 = "#804400"; // Color representing response status code 103 (yellow.70).
export const KUI_STATUS_COLOR_307 = "#fff296"; // Color representing response status code 103 (yellow.20).
export const KUI_STATUS_COLOR_308 = "#ffe04b"; // Color representing response status code 103 (yellow.30).
export const KUI_STATUS_COLOR_400 = "#ffc2b3"; // Color representing response status code 400 (orange.20).
export const KUI_STATUS_COLOR_401 = "#ff9877"; // Color representing response status code 401 (orange.30).
export const KUI_STATUS_COLOR_402 = "#ff723c"; // Color representing response status code 402 (orange.40).
export const KUI_STATUS_COLOR_403 = "#f75008"; // Color representing response status code 403 (orange.50).
export const KUI_STATUS_COLOR_404 = "#d13500"; // Color representing response status code 404 (orange.60).
export const KUI_STATUS_COLOR_405 = "#a31f00"; // Color representing response status code 405 (orange.70).
export const KUI_STATUS_COLOR_406 = "#ffc2b3"; // Color representing response status code 406 (orange.20).
export const KUI_STATUS_COLOR_407 = "#ff9877"; // Color representing response status code 407 (orange.30).
export const KUI_STATUS_COLOR_408 = "#ff723c"; // Color representing response status code 408 (orange.40).
export const KUI_STATUS_COLOR_409 = "#f75008"; // Color representing response status code 409 (orange.50).
export const KUI_STATUS_COLOR_410 = "#d13500"; // Color representing response status code 410 (orange.60).
export const KUI_STATUS_COLOR_411 = "#a31f00"; // Color representing response status code 411 (orange.70).
export const KUI_STATUS_COLOR_412 = "#ffc2b3"; // Color representing response status code 412 (orange.20).
export const KUI_STATUS_COLOR_413 = "#ff9877"; // Color representing response status code 413 (orange.30).
export const KUI_STATUS_COLOR_414 = "#ff723c"; // Color representing response status code 414 (orange.40).
export const KUI_STATUS_COLOR_415 = "#f75008"; // Color representing response status code 415 (orange.50).
export const KUI_STATUS_COLOR_416 = "#d13500"; // Color representing response status code 416 (orange.60).
export const KUI_STATUS_COLOR_417 = "#a31f00"; // Color representing response status code 417 (orange.70).
export const KUI_STATUS_COLOR_418 = "#ffc2b3"; // Color representing response status code 418 (orange.20).
export const KUI_STATUS_COLOR_421 = "#ff9877"; // Color representing response status code 421 (orange.30).
export const KUI_STATUS_COLOR_422 = "#ff723c"; // Color representing response status code 422 (orange.40).
export const KUI_STATUS_COLOR_423 = "#f75008"; // Color representing response status code 423 (orange.50).
export const KUI_STATUS_COLOR_424 = "#d13500"; // Color representing response status code 424 (orange.60).
export const KUI_STATUS_COLOR_425 = "#a31f00"; // Color representing response status code 425 (orange.70).
export const KUI_STATUS_COLOR_426 = "#ffc2b3"; // Color representing response status code 426 (orange.20).
export const KUI_STATUS_COLOR_428 = "#ff9877"; // Color representing response status code 428 (orange.30).
export const KUI_STATUS_COLOR_429 = "#ff723c"; // Color representing response status code 429 (orange.40).
export const KUI_STATUS_COLOR_431 = "#f75008"; // Color representing response status code 431 (orange.50).
export const KUI_STATUS_COLOR_451 = "#d13500"; // Color representing response status code 451 (orange.60).
export const KUI_STATUS_COLOR_500 = "#ffabab"; // Color representing response status code 500 (red.20).
export const KUI_STATUS_COLOR_501 = "#ff7272"; // Color representing response status code 501 (red.30).
export const KUI_STATUS_COLOR_502 = "#ff3954"; // Color representing response status code 502 (red.40).
export const KUI_STATUS_COLOR_503 = "#f50045"; // Color representing response status code 503 (red.50).
export const KUI_STATUS_COLOR_504 = "#d60027"; // Color representing response status code 504 (red.60).
export const KUI_STATUS_COLOR_505 = "#ad000e"; // Color representing response status code 505 (red.70).
export const KUI_STATUS_COLOR_506 = "#ffabab"; // Color representing response status code 506 (red.20).
export const KUI_STATUS_COLOR_507 = "#ff7272"; // Color representing response status code 507 (red.30).
export const KUI_STATUS_COLOR_508 = "#ff3954"; // Color representing response status code 508 (red.40).
export const KUI_STATUS_COLOR_510 = "#f50045"; // Color representing response status code 510 (red.50).
export const KUI_STATUS_COLOR_511 = "#d60027"; // Color representing response status code 511 (red.60).
export const KUI_STATUS_COLOR_1NA = "#eefaff"; // Color for unknown response status codes in the 100-199 range (blue.10).
export const KUI_STATUS_COLOR_2NA = "#ecfffb"; // Color for unknown response status codes in the 200-299 range (green.10).
export const KUI_STATUS_COLOR_3NA = "#fffce0"; // Color for unknown response status codes in the 300-399 range (yellow.10).
export const KUI_STATUS_COLOR_4NA = "#fff1ef"; // Color for unknown response status codes in the 400-499 range (orange.10).
export const KUI_STATUS_COLOR_5NA = "#ffe5e5"; // Color for unknown response status codes in the 500-599 range (red.10).
export const KUI_STATUS_COLOR_100S = "#5f9aff"; // Color for a group of response status codes in the 100-199 range (blue.40).
export const KUI_STATUS_COLOR_200S = "#00d6a4"; // Color for a group of response status codes in the 200-299 range (green.40).
export const KUI_STATUS_COLOR_300S = "#ffc400"; // Color for a group of response status codes in the 300-399 range (yellow.40).
export const KUI_STATUS_COLOR_400S = "#ff723c"; // Color for a group of response status codes in the 400-499 range (orange.40).
export const KUI_STATUS_COLOR_500S = "#ff3954"; // Color for a group of response status codes in the 500-599 range (red.40).
export const KUI_STATUS_COLOR_BACKGROUND_100 = "#eefaff"; // Background color for http status 100 elements (blue.10).
export const KUI_STATUS_COLOR_BACKGROUND_200 = "#ecfffb"; // Background color for http status 200 elements (green.10).
export const KUI_STATUS_COLOR_BACKGROUND_300 = "#fffce0"; // Background color for http status 300 elements (yellow.10).
export const KUI_STATUS_COLOR_BACKGROUND_400 = "#fff1ef"; // Background color for http status 400 elements (orange.10).
export const KUI_STATUS_COLOR_BACKGROUND_500 = "#ffe5e5"; // Background color for http status 500 elements (red.10).
export const KUI_STATUS_COLOR_TEXT_100 = "#0044f4"; // Text color for http status 100 elements (blue.60).
export const KUI_STATUS_COLOR_TEXT_200 = "#007d60"; // Text color for http status 200 elements (green.60).
export const KUI_STATUS_COLOR_TEXT_300 = "#995c00"; // Text color for http status 300 elements (yellow.60).
export const KUI_STATUS_COLOR_TEXT_400 = "#d13500"; // Text color for http status 400 elements (orange.60).
export const KUI_STATUS_COLOR_TEXT_500 = "#d60027"; // Text color for http status 500 elements (red.60).
export const KUI_FONT_FAMILY_CODE = "'JetBrains Mono', Consolas, monospace"; // The standard monospace text font family. Typically used for code blocks, inline code, and copyable text.
export const KUI_FONT_FAMILY_HEADING = "'Inter', Roboto, Helvetica, sans-serif"; // The standard heading text font family.
export const KUI_FONT_FAMILY_TEXT = "'Inter', Roboto, Helvetica, sans-serif"; // The standard text font family.
export const KUI_FONT_SIZE_10 = "10px";
export const KUI_FONT_SIZE_20 = "12px";
export const KUI_FONT_SIZE_30 = "14px";
export const KUI_FONT_SIZE_40 = "16px";
export const KUI_FONT_SIZE_50 = "18px";
export const KUI_FONT_SIZE_60 = "20px";
export const KUI_FONT_SIZE_70 = "24px";
export const KUI_FONT_SIZE_80 = "32px";
export const KUI_FONT_SIZE_90 = "40px";
export const KUI_FONT_SIZE_100 = "48px";
export const KUI_FONT_WEIGHT_BOLD = "700"; // 700: The bold font weight.
export const KUI_FONT_WEIGHT_MEDIUM = "500"; // 500: The medium font weight.
export const KUI_FONT_WEIGHT_REGULAR = "400"; // 400: The normal font weight.
export const KUI_FONT_WEIGHT_SEMIBOLD = "600"; // 600: The semibold font weight.
export const KUI_ICON_COLOR_DANGER = "#f50045"; // Danger color for icons.
export const KUI_ICON_COLOR_NEUTRAL = "#828a9e"; // Neutral color for icons.
export const KUI_ICON_COLOR_PRIMARY = "#306fff"; // Primary color for icons.
export const KUI_ICON_COLOR_SUCCESS = "#00a17b"; // Success color for icons.
export const KUI_ICON_COLOR_WARNING = "#ffc400"; // Warning color for icons.
export const KUI_ICON_SIZE_10 = "10px"; // 10px icon size.
export const KUI_ICON_SIZE_20 = "12px"; // 12px icon size.
export const KUI_ICON_SIZE_30 = "16px"; // 16px icon size.
export const KUI_ICON_SIZE_40 = "20px"; // 20px icon size.
export const KUI_ICON_SIZE_50 = "24px"; // 24px icon size (default).
export const KUI_ICON_SIZE_60 = "32px"; // 32px icon size.
export const KUI_ICON_SIZE_70 = "40px"; // 40px icon size.
export const KUI_ICON_SIZE_80 = "48px"; // 48px icon size.
export const KUI_LETTER_SPACING_0 = "normal"; // Alias for letter-spacing-normal
export const KUI_LETTER_SPACING_MINUS_10 = "-0.12px"; // -0.12px
export const KUI_LETTER_SPACING_MINUS_20 = "-0.24px"; // -0.24px
export const KUI_LETTER_SPACING_MINUS_30 = "-0.32px"; // -0.32px
export const KUI_LETTER_SPACING_MINUS_40 = "-0.4px"; // -0.4px
export const KUI_LETTER_SPACING_MINUS_50 = "-0.48px"; // -0.48px
export const KUI_LETTER_SPACING_NORMAL = "normal"; // normal
export const KUI_LINE_HEIGHT_10 = "12px"; // 12px
export const KUI_LINE_HEIGHT_20 = "16px"; // 16px
export const KUI_LINE_HEIGHT_30 = "20px"; // 20px
export const KUI_LINE_HEIGHT_40 = "24px"; // 24px
export const KUI_LINE_HEIGHT_50 = "28px"; // 28px
export const KUI_LINE_HEIGHT_60 = "32px"; // 32px
export const KUI_LINE_HEIGHT_70 = "36px"; // 36px
export const KUI_LINE_HEIGHT_80 = "40px"; // 40px
export const KUI_LINE_HEIGHT_90 = "48px"; // 48px
export const KUI_LINE_HEIGHT_100 = "56px"; // 56px
export const KUI_NAVIGATION_COLOR_BACKGROUND = "#000933"; // blue.100
export const KUI_NAVIGATION_COLOR_BACKGROUND_SELECTED =
  "rgba(255, 255, 255, 0.12)"; // The background color of a selected navigation item.
export const KUI_NAVIGATION_COLOR_BORDER = "rgba(255, 255, 255, 0.12)"; // rgba(255, 255, 255, 0.12)
export const KUI_NAVIGATION_COLOR_BORDER_CHILD = "#00fabe"; // The border color for a selected child navigation item.
export const KUI_NAVIGATION_COLOR_BORDER_DIVIDER = "rgba(255, 255, 255, 0.24)"; // The color of the navigation section divider.
export const KUI_NAVIGATION_COLOR_TEXT = "#bee2ff"; // Navigation link and icon color.
export const KUI_NAVIGATION_COLOR_TEXT_FOCUS = "#ffffff"; // Navigation link and icon focus-visible color.
export const KUI_NAVIGATION_COLOR_TEXT_HOVER = "#eefaff"; // Navigation link and icon hover color.
export const KUI_NAVIGATION_COLOR_TEXT_SELECTED = "#00fabe"; // Navigation link and icon selected color.
export const KUI_NAVIGATION_SHADOW_BORDER =
  "0 0 0 1px rgba(255, 255, 255, 0.12) inset"; // The box-shadow for a focus-visible navigation link.
export const KUI_NAVIGATION_SHADOW_BORDER_CHILD = "4px 0 0 0 #00fabe inset"; // The left box-shadow for an active child navigation link.
export const KUI_NAVIGATION_SHADOW_FOCUS =
  "0 0 0 1px rgba(255, 255, 255, 0.60) inset"; // Navigation link focus-visible box-shadow.
export const KUI_SHADOW = "0px 4px 20px 0px rgba(0, 0, 0, 0.08)"; // 0px 4px 20px 0px rgba(0, 0, 0, 0.08)
export const KUI_SHADOW_BORDER = "0px 0px 0px 1px #e0e4ea inset"; // 0px 0px 0px 1px gray.20 inset
export const KUI_SHADOW_BORDER_DANGER = "0px 0px 0px 1px #d60027 inset"; // 0px 0px 0px 1px red.60 inset
export const KUI_SHADOW_BORDER_DANGER_STRONG = "0px 0px 0px 1px #ad000e inset"; // 0px 0px 0px 1px red.70 inset
export const KUI_SHADOW_BORDER_DISABLED = "0px 0px 0px 1px #e0e4ea inset"; // 0px 0px 0px 1px gray.20 inset
export const KUI_SHADOW_BORDER_PRIMARY = "0px 0px 0px 1px #0044f4 inset"; // 0px 0px 0px 1px blue.60 inset
export const KUI_SHADOW_BORDER_PRIMARY_STRONGEST =
  "0px 0px 0px 1px #001466 inset"; // 0px 0px 0px 1px blue.90 inset
export const KUI_SHADOW_BORDER_PRIMARY_WEAK = "0px 0px 0px 1px #5f9aff inset"; // 0px 0px 0px 1px blue.40 inset
export const KUI_SHADOW_FOCUS = "0px 0px 0px 4px rgba(0, 68, 244, 0.2)"; // 0px 0px 0px 4px rgba(0, 68, 244, 0.2)
export const KUI_SPACE_0 = "0px"; // 0px value for gaps, margin, or padding.
export const KUI_SPACE_10 = "2px"; // 2px value for gaps, margin, or padding.
export const KUI_SPACE_20 = "4px"; // 4px value for gaps, margin, or padding.
export const KUI_SPACE_30 = "6px"; // 6px value for gaps, margin, or padding.
export const KUI_SPACE_40 = "8px"; // 8px value for gaps, margin, or padding.
export const KUI_SPACE_50 = "12px"; // 12px value for gaps, margin, or padding.
export const KUI_SPACE_60 = "16px"; // 16px value for gaps, margin, or padding.
export const KUI_SPACE_70 = "20px"; // 20px value for gaps, margin, or padding.
export const KUI_SPACE_80 = "24px"; // 24px value for gaps, margin, or padding.
export const KUI_SPACE_90 = "32px"; // 32px value for gaps, margin, or padding.
export const KUI_SPACE_100 = "40px"; // 40px value for gaps, margin, or padding.
export const KUI_SPACE_110 = "48px"; // 48px value for gaps, margin, or padding.
export const KUI_SPACE_120 = "56px"; // 56px value for gaps, margin, or padding.
export const KUI_SPACE_130 = "64px"; // 64px value for gaps, margin, or padding.
export const KUI_SPACE_140 = "80px"; // 80px value for gaps, margin, or padding.
export const KUI_SPACE_150 = "96px"; // 96px value for gaps, margin, or padding.
export const KUI_SPACE_AUTO = "auto"; // auto
