name: Setup PNPM with Dependencies
description: Reusable composition of setup-node, cache, and pnpm install actions
inputs:
  nodejs-version:
    description: 'Version of NodeJS to use (ex: 20.16.0)'
    default: '20.16.0'
  force-install:
    description: When 'true', pnpm install will be executed regardless of a cache hit
    required: false
    default: 'false'
  frozen-lockfile:
    description: When false, pnpm install will use the --no-frozen-lockfile flag
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: Whether or not there was a cache hit
    value: ${{ steps.dependency-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:

    - name: get Node version
      id: node-version
      shell: bash
      run: |
        voltaNodeVersion=$(cat package.json|jq -r ".volta.node")
        if [[ $voltaNodeVersion == null ]]; then
          voltaNodeVersion="${{ inputs.nodejs-version }}"
        fi
        packageManagerVersion=$(cat package.json|jq -r ".packageManager")
        if [[ $packageManagerVersion == null ]]; then
          packageManagerVersion="9.7.0"
        fi

        echo "node-version=${voltaNodeVersion}">> $GITHUB_OUTPUT
        echo "package-manager-version=${packageManagerVersion}">> $GITHUB_OUTPUT

    - name: Setup Node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ steps.node-version.outputs.node-version }}

    - name: Install PNPM
      shell: bash
      run: |
        npm i -g ${{ steps.node-version.outputs.package-manager-version }}
        pnpm --version

    - name: Dependency Cache
      id: dependency-cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: '**/node_modules'
        key: ${{ steps.node-version.outputs.package-manager-version }}-${{ steps.node-version.outputs.node-version }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      if: ${{ inputs.force-install == 'true' || steps.dependency-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: pnpm i${{ inputs.frozen-lockfile == 'false' && ' --no-frozen-lockfile' || '' }}
