name: On closing PR
on:
  pull_request:
    types: ['closed']

permissions:
  pull-requests: write

jobs:
  unpublish:
    name: Remove preview consumption comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Remove preview comment — @kong/design-tokens
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: pr_preview_@kong/design-tokens
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Remove preview comment — @kong/stylelint-plugin-design-tokens
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: pr_preview_@kong/stylelint-plugin-design-tokens
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Remove preview comment — @kong/eslint-plugin-design-tokens
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: pr_preview_@kong/eslint-plugin-design-tokens
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
