name: Test

on:
  # Allow workflow to be called by another workflow
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/
        with:
          force-install: true

      - name: Lint
        run: pnpm lint

      - name: Build tokens package
        run: pnpm build

      # Must build before the typecheck since the files are needed for the sandbox
      - name: Typecheck
        run: pnpm typecheck

      - name: Build sandbox
        env:
          # Tell the script to use the sandbox directory
          BUILD_SANDBOX: true
        run: pnpm sandbox:build

      - name: Upload tokens package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tokens-package
          path: dist/
          retention-days: 1

      - name: Upload sandbox
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sandbox
          path: sandbox/dist/
          retention-days: 1
